### ISSUE TITLE
Open to a reverse iterator?

### ISSUE THREAD

**Issue by evanpurkhiser** [cuu508/cronsim#2]
We're using `croniter` right now for Sentry's cron monitoring feature but would be interested in using `cronsim` due to it's more modern and simple python codebase.

Would you be open to a PR that implements reverse iteration? I suspect this would be as simple as adding a new constructor argument `reverse=True` and subtracting in each advance function instead of adding.

I realize you explicitly called out NOT implementing this, which is why I am asking :)

> Don't implement features that Healthchecks will not use (for example, iteration in reverse, or the seconds field in cron expressions).

**Comment by cuu508** [comment]
Thanks for showing the interest!

I currently do not need reverse iteration for my use case, but if it's something that is commonly needed, and is not too cumbersome to implement, I'm open to adding it.

Out of curiosity, in what situations do you need to iterate backwards in Sentry? 

I prototyped backwards iteration [in a separate branch](https://github.com/cuu508/cronsim/tree/reversing). Rather than packing the addition and subtraction logic in the `advance_minute`, `advance_hour` etc. methods, to me it looks cleaner if there are separate `reverse_minute`, `reverse_hour` etc. methods. The prototype has the bare minimum to work, these could be optimized for speed.

The neat thing is the correctness of backwards iteration can be tested by using the normal forwards iterator. I wrote a small script which goes through a corpus of cron expressions, and for each iterates 1000 times forward, and then 1000 times backward, and makes sure everything matches up. And with the expressions I tested with everything did indeed match up :-)

**Comment by cuu508** [comment]
I did some more work on tidying up the implementation, merged it into main, and released as cronsim 2.6.

**Comment by evanpurkhiser** [comment]
Oh wow! Thanks so much @cuu508

**Comment by evanpurkhiser** [comment]
> Out of curiosity, in what situations do you need to iterate backwards in Sentry?

It's a bit tricky to explain and probably requires a pretty deep understanding of our system but I'll give it a shot.

The way we handle determining misses is from a clock that is driven by the event stream of check-ins (eg, if that stream is backlogged the clock ticking slows down, we only tick once we know we've processed all check-ins for a particular minute). Each time it ticks we look for all monitors that have their `next_expected_check_in_time` less than when the clock tick was. That time moves forward every time they check in, and is what we use croniter to compute.

Typically when the clock ticks next we would create a missed check-in with it's timestamp set to `next_expected_check_in_time` since that's when the monitor should have checked in.

There are some edge cases (though very few if any now after more work I think) where we may skip a clock tick. In those cases when we skip and we don't report some missed check ins, when the `next_expected_check_in_time` is not actually the time the miss that we're ticking past should be reported for. So we instead compute when the previous cron tick was from the time we just ticked past, using the reverse iteration.

This is also a consideration when the monitor has a missed margin time longer than it's schedule. For example a monitor runs once a minute, but has a margin of 5m (I realize this doesn't make sense, and our system probably should restrict this, but we don't yet). In those cases we would only create a miss every 5 minutes, but in order to correctly keep the `next_expected_check_in_time` moving forward after a miss we have to compute the next expected check-in for the monitor based on the most recent expected time.

---

Not sure if all that makes sense. Either way, thank you so much for getting that into master. There's going to be one other thing that I think will block us from migrating to cronsim, but i'll open a separate issue / create a PR for that :)

Thank you so much for this library and making it open source!
